language: python
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.cache/pip"
python:
- '2.7'
addons:
  apt:
    packages:
    - expect-dev
    - python-lxml
    - python-simplejson
    - python-serial
    - python-yaml
    - sshpass
  postgresql: '9.3'
env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0" OPTIONS="--test-report-directory=${HOME}/tests"
    EXCLUDE="xml_test_output"
  - secure: pqiKNs/ThGodrO83snBuPJUqnt3E2kEjUEUJfIkNRVBDoTsIdfLx9xmwRbKk8/mihOOhc+ks6Mx6dUTH1+tXf3Mj4X/P8OuiAbL1aRK6liVK5ItzjS4nmHMgGSY7GVZQk2r0NZWiUdiGGdMkkxtJwhVE7leMS9hNyh+vXLB3xJrHV0qQkWYE3yILAWs5atRrU3RiD1vXY2xvmrUFFTQKOuk4XrZA4Hu9gi+GnekBTbHRQRRynklrQ4CFANRpYIRHqRAY3vKg/3rqKByVS+BPffZW9z2KokV4UrAnxePTC114/9zBEAfI6cw5smryFoUqOLc6cqukXZ8oW0+bPVvsGrR85U9eY2Vz7/es2f9spUmmbjxkj5nSmxIENlc7XlhmCXDAiD+MTU1cUEVuk1eXtm2Nyo0G8t3ql2VUEGvPw916kNvP58qNXdtQGYstU8Gnxc8xvi4lQkqCMFy1Eszd9P9pWqO95XB8WLApOOqW+IuhQDXa5+nxNnr9NwyE6kBDHvv202gOFe+lC0aRKlkzhqHT61CiDa/DcI+Di/3zIpLQ0g2TDOwyXbKSiibyOeEKmMBM6dfMRjPrOKsSGPeeCWSIVuY+8AUeOAOxT7qZgOaGzhU3bwttSiAwbJo8+eCUeL91BXuNWci98A8J1dRsS1n4CFNNvUjs+7p/Pa4zq7c=
  - secure: i5LWEMxf3nRnyvG+F341bwByArcoeCzSXt87DrNbNYbbmzbcDD3eh9FUJ/vX5GB61Lqy1CcrDSv1OLl4MiQGkzQqNoQL1yC2nqij9ZCj/Zfm3M/Al9bwsX9JVNLITDFsXfutu3/9g3uLl5bKNI+esVD3t3dljTAytm/fxjrZ8o/dzN+SLfm0do5Tinr80WlOXiq64mcLU50ndDoUnBYFn1iJYB1Kmt6uqvpVbnTfkIJMQH+KJFpTAiTKQXuzCoOHLL7n5t/9reJNTlncgvpnoYhr0irVFRnqxok3YdtOd7qjpjQuXxqRjvR9ZP9+13ZXzgJwMnvInfnjo/edfGyudA3eZDkaBHbQUj+p61SOJPr4vZ4oWFLi+0p2FvaNZuhcamGRBx2YHWrUCAZWM3GkMSzaGY5MefShb6WFDIgDuzd044FDtMOjTJzX7T3A5OGFRvNzAhWF4YySyyMzfegt1WuUDRNQy1mnKF0YWy5YqckXD5R9s420o1OaPi9r1BppMlPAHHgL2QX6fAsEBfEzhh2o2gg45Fgqdibyb9KhTbY71BE4TPflSP67HZhad0wOIu+Vz/5UGkLra1A5DHmiSdfyxcsudx7G5UQU5WF22adAhZp9QW2IGvRh1XW9VbbmmLI/5urW+IlWDQlRu5fmsozXG3fiO9iJL9amfH6x9l8=
  - secure: LPDRZjj97Y8D860h9GkDoYc+FaJwWzaBzWp/QRLk2ZpyHD0ewbnnLkcjDvCkaFIoUNh61yrYCuNKEMNzSC7RlCYmxzdRSpkwZcKdPU3NIxS+wB4HSKOAOEIfFhcKvH5M3BUBEIIO+qmUy4YMBzPqM5TZbBr/adMqzdv6m42zisXhacJYwJDhCkOcGwcqiH8A3TQdyBrK/oS18fd1lXiunyG+xOAuakYlOzxvPKDaAnB/XFDyPSLwB8FS9K/+CmFAzgfRQlg2uH6Ipn/T7eOja4YfLKdSoPFZxph/Inu480rZtyllxFHHyxZE73LV1rRs6Q5Y3VyskLCSRvTv6GjABZ3jSMwSkZEg/CKnDcYpFT9k5Aqg7pybB3XaOYsea3Uaby16oijMR3lHxTLLCTIDETJKO0+RNMvnQd4nFYrJh6+RzH0y5fJYEkNU8bFylkTSJDFU30UOSfut9nxbiQi3/NN+IQsHSs0R6drZxjuSXc55AuT2AvUt1ByGE8G9WNNircCyxazxy+NBwR2C7Ubque2e9aMC0ZbgERZ+Qd0Cww2FQ01fdgsIcxMbgF9RNFXSTDnrl/TPaXlX5RG4LRQE40eoKQBBY7wGEgUFbEiAIImFg+Mr/I2h5tdI6H9C2D79wPzo0Po3Rm34q7jaHPwNULtC6Zz6Pl1t69F+b0ESn60=
  - secure: WodYMhx8q74WZbdXYyHC4NzraBvxB3/Pe1G4n+NgFfw0WiazT7N3hbi4l1srLocaBo0sYVg/revpUIf9sq+K6pxOokBpOL6t4msK3WT7pCECnrZgj9MYWz7UemyQMj9whSVC46GBHxdhatJLvSfUut7AOvYpQPwgIbflbTttqlyYqyS3OJcpZ6yB8Sd6HIRF2Hu+vRuk7YII6a3otYapiv1+9Gsai3QCmKHkwj+qqFMEzCayt2U7lKfTc0WMdetAKV08tgEIHs3nf/LfPBK9s+oeFuwbWquhK9/Gwv57KwYyySR5pHZhU3K/3RsAN6KM+AnsGFA0iGgKcqbhOypVdayZ4Er32LOdydf3uQ5i86Y7g97E9Gfzb4fyd7Nnu3QmYUe81Dl1KEFoUvwqhVaZsOGbZnZEoBd5qCi8wJDHNroVjO8hD9L6sT43FBO93NiSiXnoU0wEbFBWRtqzSgabFQn53WD3159BZ+WdTls9GnYmQaj8onW+3JPbIDtsVwxoJdoiuRqdCbUTsdLAQFoJdaVOC+UpS4ijXzZ2byRLcnbRQJCUlHYaqfpNHSrqI4pwyCo5Q3PozzA4OsEuBrY/MBmRbtGqTxHHMotT98JjSNzwRPKssR50IdD2t2VS4tZBOUtJr8VlLh40Q7CirKmp+BjG2GbrpZyRePAvgTaykZo=
  - secure: PyUT10yCab9BjFvDhYTvsF7Jh/0ZTvPlR4opKg7xS5+TTa8ph5VrlEcfJnbm1QpNI19e+cNgZyIWKFna4JEP9a2p/w4u0ZNTMWGJ44c3oSEmkeQenUTvCxkP8l4HQoSc/4TBuc58jYmotpHk1fgY45SzBHC3oI5zlofrMCrMQerJVmhGQYP1r6KJxgI48Z8X0kcyyWIKBIy384Flm2VYCVd0m2K3ewCXQXB5qH3pFIfzDYY0gxSgASBjrroj+W5sWVDE/HWseS06YtOXV6lRH1DYeVGzHGur3CVeeenu7ygde5Y5yYeb2ofVc0wZ0mYTY1kjY0neqgQJBLSHe6AbHKSBAnKaQHsm7Md9Nr/oV/YCiXAN4BKmCnOb6jPHyPikX4LFrVvdvLGm9+jhRWMl2tMXZM3325RLcL+lJdDSWhrpatZHgbMvLoUh4BZdlOUl/k+PUqngarrt9nBszHzl+VY/FSJ2TTja9s2j9ShsS9ydJmqC5bpG0NxwN7YXCGt2Q2L2H5MbOAQclkXsw3lRZtvErKksZbCip1qRQGfnnGuAEwb4cKgP8P6v8FEgMTL/0SaLifOuwiPXdO+Z+SY/FUbY5/OjXQBixL4E41/MJ+1kX4tU/EZh0GxdlWLvBgVYP+xJ32LoYiLhQbXy7iBlNLonG7z/u+ztOZOJE4DTlS4=
  - secure: vwGMJpupwg6F1SDtakLBuCijJL5azeqa/8wz7wppCHR+Cnvgb9VY/LWtT1L+yFK839gRv/k2jkTz34lAC7wijVMHng6hLpiefLar72+QrLd+BcJw8/PvxNgL/fqQzHKw89YjzZCStFNOZ9fTdOR0dbgxbkAufVCeYbtjyP3lfl3tumyCa/5Yii/1NRituYcA2+4Pgofq/RYfBpp4JwitFOjqrOHsqfsmDnboDv9GVSL4HLeZHJoim+nJaSm5Ox/QKymsQVyOQtRhfqpJejThx7y0RWFQqq4Hx3wW4GIwAMpLqBL1i84Wdt6oYZWRHsmx5qTADIMKCSs3vlFgx4tyfVH4LkfVmK7okcwqulVd1BQbSh1CFG/fdT76yF9Lz70LANHcAclIN0ye17+mTjKpMX2Jfd7Frt3/ModviyqGj3oDRiUWdkgeC5jC1nypYDa1tF4NDyMDV0rGWu+fUqjsl7HdyMDRGjT4g9S7tPlrsfRdRQ172q4BmBubfyjdrcmBWW9tgazcI4/A/Me1ufypSFIELLAC+MQeJ9b7fMAnNqT/Qojw5+FpqyQroaDedl4p3qx4ZnIIYA26ofQGwJNoS4SoBlO7imMjk2U4BDP/94jMxBE0MFfFk6SKQ7jIK9VK5LaO6mYyCeiCXgVOfh+g4y5Qb0CgHN0rrCWiLG3/CP0=
  - secure: ABS3Q7nYq0kOdONqhx6urSAK1oF/zgxrl1PZBPsFsyOGeMC1cKuOF0jbubJPH4Pssf1iD8LaVhTWvbrfusO1SiAiSyQOvENfyW1bmlc+Bw3mw4XraMkyllC4k4CwGzp62iJp5nCq1XkpdzrcMcyGrUmaqB6gBVNP3h/bOWgCtxGi+m4WCRzXtpd522coTDLicq3YCIFIzn56tHEg+2/qcaoFpQsG035I8DhmI05ZA3YwBcdPjQq23pce1+C6PX9tlie/+/4ipBFSZzRb4yBeNk7XPtANgKITwqv76i8ML17pW3IY35BXHDeviNEuk9ksDAARfxT+cfg9Yu28L4bf14M9v+/LuC0L9L6Zt2d0ge82raUHF+vBdxDhkfPcLRdw8dyuesuPK32BIhu/h/vNw3jW4bh/lutxKyjZU4V3roP8IOfZ9p2Whl6iAIWyG2V9/vmbQKHzJMQRx9ziA9Cho3/NptdiS6XxwRJm7Ls+UOa3OHS+6wzoXaJkAHdOPsHCDwXEFHBjH7FglllsO2Fmit9t6J8NIDKYHMD4uOupIdy9d45hTusOjbAQSWYqVBxzhBRlFnj52webN7dOisU31+C79leTUbcMCzAeo/YqdS9KFQ9jFSkWOLLjBGOwFcMaACBbEIjV2n5I9cJbZvvAYp2NbaS0qMpxLb/3LUztpAs=
  - secure: nsQcUUTiq3z9ZureyXwrILRca2lERtUNDkS52N77NS8NTJOciKMCzKAOGPaDgnIQU0ZQdvyxj8PpqkeQpwJSxfrh6ccC1zpHCayhGHxgGxcZGWUkV6gr3d4CVURgerAqiBeQP/Kj3Ffq6Bi5aFZeTovWGZTsx3QvK3hr+5yO2kVpNQ4VdErnle4BI+/pi5GQZ56n9wrdUX6YHRjUk1Nmtbvt5ixrMSM0p3X1LmZWO2vF6csuSGkuO1QQgjfRb1PTUOEtIOl9Gsv3nq/roHdGYEHp3aBHJplVYWic7OKfyCreI4FjafYeC/DelrCLnStow+bBuSpBYA34Ukv1Aj103j+QuYGWNpix73P4E7mQiXlfKA8+lneitS0QSfD5byGRqVQcnKyn4LlGjuFhNponShsmiwrsFDfbmmY5Ysdi4Gi2nVaXX5M+y620tlfV+vgtAa6/PoXKVr0NSVCWbMmyn79L/a1tQxNX09gy/YbreNGM2dYS5qOrI0OxaU7K7Y3GrczvV8/7QiE9SoVGIT/7rVQ3pN4uaY0xWGBsJGCab9B50xPbOe8VeJIqFcJF3kkEQ8kYjoAgXimXqXm1Yqqim0pvlSMRAS6Lugi8HU7WcbNV18/2PY7cj5I4Y/wc+MtUQ9Wo1LYX/o0UN+9RNiR5/hXAU+rEKMRIEks5bhVeGpw=
  matrix:
  - LINT-CHECK="1"
  - ODOO_REPO="valdecdev/odoo" TESTS="1" INCLUDE="nh_odoo_fixes,nh_activity,nh_clinical"
    VERSION="openeobs-8-12" SERVER_EXPECTED_ERRORS="1"
virtualenv:
  system_site_packages: true
before_install:
- wget http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip
- unzip sonar-runner-dist-2.4.zip
- mv sonar-runner-2.4 ${HOME}/sonar-runner-2.4
- rm ${HOME}/sonar-runner-2.4/conf/sonar-runner.properties
- echo -e "sonar.host.url=${SONAR_URL}\nsonar.jdbc.username=${SONAR_USER}\nsonar.jdbc.password=${SONAR_PASSWORD}\nsonar.jdbc.url=${SONAR_DBURL}"
  >> ${HOME}/sonar-runner-2.4/conf/sonar-runner.properties
- git clone --depth=50 https://github.com/Gimpneek/odoo_xml_test_output.git odoo_xml_test_output
- cd odoo_xml_test_output
- pip install -r requirements.txt
- mkdir -p ${HOME}/dependencies
- mv xml_test_output ${HOME}/dependencies/xml_test_output
- cd ${TRAVIS_BUILD_DIR}
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
- export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
- travis_install_nightly
script:
- travis_run_tests
after_script:
- coverage xml -o ${HOME}/build/NeovaHealth/nhclinical/coverage.xml
- cd ${HOME}/build/NeovaHealth/nhclinical
- echo "<?xml version=\"1.0\" encoding=\"utf-8\"?><testsuites>" > test_report.xml
- for rep in ${HOME}/tests/*.xml; do cat "$rep" | grep -v "<?xml " >> test_report.xml;
  done
- echo "</testsuites>" >> test_report.xml
- echo -e "\nsonar.python.coverage.reportPath=coverage.xml" >> sonar-project.properties
- echo -e "\nsonar.python.xunit.reportPath=test_report.xml" >> sonar-project.properties
- ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST -L 2000:localhost:2000 -L 6432:localhost:5432 -fN
- "${HOME}/sonar-runner-2.4/bin/sonar-runner"