language: python
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.cache/pip"
python:
- '2.7'
addons:
  apt:
    packages:
    - expect-dev
    - python-lxml
    - python-simplejson
    - python-serial
    - python-yaml
    - sshpass
  postgresql: '9.3'
env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0" OPTIONS="--test-report-directory=${HOME}/tests"
    EXCLUDE="xml_test_output"
  matrix:
  - LINT_CHECK="1"
  - ODOO_REPO="valdecdev/odoo" TESTS="1" INCLUDE="nh_odoo_fixes,nh_activity,nh_clinical"
    VERSION="openeobs-8-12"
virtualenv:
  system_site_packages: true
before_install:
- git clone --depth=50 https://github.com/Gimpneek/odoo_xml_test_output.git odoo_xml_test_output
- cd odoo_xml_test_output
- pip install -r requirements.txt
- mkdir -p ${HOME}/dependencies
- mv xml_test_output ${HOME}/dependencies/xml_test_output
- cd ${TRAVIS_BUILD_DIR}
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
- export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
- travis_install_nightly
script:
- travis_run_tests
after_script:
- coverage xml -o ${HOME}/build/NeovaHealth/nhclinical/coverage.xml
- cd ${HOME}/build/NeovaHealth/nhclinical
- echo "<?xml version=\"1.0\" encoding=\"utf-8\"?><testsuites>" > test_report.xml
- for rep in ${HOME}/tests/*.xml; do cat "$rep" | grep -v "<?xml " >> test_report.xml;
  done
- echo "</testsuites>" >> test_report.xml

- echo "hello, world!" >> test_file.xml
- echo "${TRAVIS_REPO_SLUG} ${TRAVIS_BUILD_NUMBER} ${TRAVIS_BRANCH} ${TRAVIS_COMMIT}" >> test_file.xml
- echo "{\"branch\":\"${TRAVIS_BRANCH}\",\"type\":\"push\",\"commit\":\"${TRAVIS_COMMIT}\",\"message\":\"test_message\",\"pull_request\":\"${TRAVIS_PULL_REQUEST}\",\"committer_name\":\"John_Smith\",\"repository\":{\"name\":\"${TRAVIS_REPO_SLUG}\",\"url\":\"http://test_url.com\"}}" > json.file
- if [ "$TRAVIS_TEST_RESULT" == "0" ];  then curl ${TARGET_URL}:8080/$TARGET_JOB --user $TARGET_USER:$TARGET_PASSWORD -F coverage_report_file=@./${HOME}/build/NeovaHealth/nhclinical/coverage.xml -F json_file=@./json.file -F test_report_file.xml=@./test_report.xml -F json='{"parameter":[{"name":"coverage_report","file":"coverage_report_file"}, {"name":"json_payload","file":"json_file"}, {"name":"test_report","file":"test_report_file"}]}'; fi

